// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shwcmivyidzvunvittxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNod2NtaXZ5aWR6dnVudml0dHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTc0MDQsImV4cCI6MjA2ODk3MzQwNH0.dT31AU2nXpwc26kW_4vlB4LgP24JQvtz1UzidjLyM5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});